language: python
python:
    - 3.6
cache: pip
addons:
  apt:
    packages:
      # java8 is required for elasticsearch
      - oracle-java8-set-default
before_install:
  # adapted from https://github.com/peterbe/autocompeter/blob/master/.travis.yml
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.2.1.deb && sudo dpkg -i --force-confnew elasticsearch-6.2.1.deb && sudo service elasticsearch start
install: make install
script:
  - make integration-test
