version: '2'

services:
  web:
    build: web/
    ports:
      - "8000:8000"
    links:
      - redis
    depends_on:
      - logspout
    volumes:
      - ./web:/code:ro

  nginx:
    restart:
      always
    build:
      nginx/
    ports:
      - "80:80"
    volumes:
      - ./web/static:/www/static:ro
    depends_on:
      - web

  redis:
    image: redis:3.0

  logspout:
    build: logspout/
    environment:
      ROUTE_URIS: syslog://logs4.papertrailapp.com:31896
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
