version: '2'

services:
  web:
    build:
      ./web
    image:
      topher200/assertion-context
    env_file:
      ./.env
    restart:
      always

  celery:
    build:
      ./web
    image:
      topher200/assertion-context
    env_file:
      ./.env
    restart:
      always
    command:
      [celery, -A, app.tasks, worker]

  realtime-updater:
    build:
      context:
        ./web
      dockerfile:
        Dockerfile-realtime-updater
    image:
      topher200/assertion-context-realtime-updater
    env_file:
      ./.env
    restart:
      always

  nginx:
    restart:
      always
    build:
      ./nginx
    ports:
      - "80:80"
