version: '2'

services:
  web:
    build: web/
    links:
      - redis
    depends_on:
      - logspout
    volumes:
      - ./web:/code:ro

  nginx:
    restart:
      always
    build:
      nginx/
    ports:
      - "80:80"
    volumes:
      - ./web/static:/www/static:ro
    depends_on:
      - web

  redis:
    image: redis:3.2

  logspout:
    image:
      gliderlabs/logspout:v3.2.1
    restart:
      always
    environment:
      ROUTE_URIS: syslog+tls://logs4.papertrailapp.com:31896
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
