version: '2'

services:
  web:
    build: web/
    restart:
      always

  celery:
    build: web/
    restart:
      always
    command:
      [celery, -A, app.tasks, worker]

  realtime_updater:
    build: web/realtime_updater/
    restart:
      always

  nginx:
    restart:
      always
    build:
      nginx/
    ports:
      - "80:80"
