version: '3.7'

services:
  web:
    image:
      topher200/assertion-context:latest
    env_file:
      ./.env
    restart:
      always

  celery:
    image:
      topher200/assertion-context:latest
    env_file:
      ./.env
    command:
      [celery, -A, tasks, worker]
    restart:
      always

  nginx:
    image:
      topher200/assertion-context-nginx:latest
    ports:
      - "80:80"
    restart:
      always
