version: '3.7'

services:
  web:
    image:
      topher200/assertion-context
    env_file:
      ./.env
    restart:
      always

  celery:
    image:
      topher200/assertion-context
    env_file:
      ./.env
    command:
      [celery, -A, app.tasks, worker]
    restart:
      always

  nginx:
    image:
      topher200/assertion-context-nginx
    ports:
      - "80:80"
    restart:
      always
