version: '2'

services:
  web:
    command: ["gunicorn", "--workers", "4", "--bind", ":8000", "server:app"]
    logging:
        driver: syslog
        options:
            syslog-address: ${PAPERTRAIL_PRODUCTION_URL}
            tag: web

  nginx:
    logging:
        driver: syslog
        options:
            syslog-address: ${PAPERTRAIL_PRODUCTION_URL}
            tag: nginx

  redis:
    logging:
        driver: syslog
        options:
            syslog-address: ${PAPERTRAIL_PRODUCTION_URL}
            tag: redis
