version: '2'

services:
  web:
    command: ["gunicorn", "--workers", "2", "--bind", ":8000", "--timeout", "60", "server:app"]
    logging:
        driver: syslog
        options:
            syslog-address: ${PAPERTRAIL_PRODUCTION_URL}
            tag: web

  celery:
    logging:
        driver: syslog
        options:
            syslog-address: ${PAPERTRAIL_PRODUCTION_URL}
            tag: celery

  realtime_updater:
    logging:
        driver: syslog
        options:
            syslog-address: ${PAPERTRAIL_PRODUCTION_URL}
            tag: realtime_updater

  nginx:
    logging:
        driver: syslog
        options:
            syslog-address: ${PAPERTRAIL_PRODUCTION_URL}
            tag: nginx

  redis:
    logging:
        driver: syslog
        options:
            syslog-address: ${PAPERTRAIL_PRODUCTION_URL}
            tag: redis
