version: '2'

volumes:
  elasticsearch:

services:
  web:
    ports:
      - "8000:8000"
    links:
      - elasticsearch
    logging:
        driver: syslog
        options:
            syslog-address: ${PAPERTRAIL_DEVELOPMENT_URL}
            tag: web

  celery:
    logging:
        driver: syslog
        options:
            syslog-address: ${PAPERTRAIL_DEVELOPMENT_URL}
            tag: celery

  nginx:
    logging:
        driver: syslog
        options:
            syslog-address: ${PAPERTRAIL_DEVELOPMENT_URL}
            tag: nginx

  redis:
    ports:
      - "6379:6379"
    logging:
        driver: syslog
        options:
            syslog-address: ${PAPERTRAIL_DEVELOPMENT_URL}
            tag: redis

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1000m -Xmx1000m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 2g
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:5.2.1
    depends_on:
      - elasticsearch
    environment:
      - xpack.security.enabled=false
    ports:
      - "5601:5601"
