version: '2'

services:
  web:
    build: web/
    links:
      - redis
    volumes:
      - ./web:/code:ro
    restart:
      always
    logging:
        options:
            tag: web

  nginx:
    restart:
      always
    build:
      nginx/
    ports:
      - "80:80"
    volumes:
      - ./web/static:/www/static:ro
    depends_on:
      - web
    logging:
        options:
            tag: nginx

  redis:
    image: redis:3.2
    restart:
      always
    logging:
        options:
            tag: redis
