version: '2'

volumes:
  elasticsearch:

services:
  web:
    build: web/
    ports:
      - "80:5000"
    links:
      - elasticsearch
    depends_on:
      - logspout

  elasticsearch:
    image: elasticsearch:latest
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    depends_on:
      - logspout

  kibana:
    build: elk/kibana/
    volumes:
      - ./elk/kibana/config/:/opt/kibana/config/
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
      - logspout

  logspout:
    build: logspout/
    environment:
      ROUTE_URIS: syslog://logs4.papertrailapp.com:35625
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
