version: '2'

services:
  web:
    build: web/
    volumes:
      - ./web:/code:ro
    restart:
      always

  celery:
    build: web/
    volumes:
      - ./web:/code:ro
    restart:
      always
    command:
      [celery, -A, app.tasks, worker]

  realtime_updater:
    build: web/realtime_updater/
    volumes:
      - ./web:/code:ro
    restart:
      always

  nginx:
    restart:
      always
    build:
      nginx/
    ports:
      - "80:80"
    volumes:
      - ./web/static:/www/static:ro
    depends_on:
      - web

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
