version: '2'

services:
  web:
    command: ["gunicorn", "--workers", "4", "--bind", ":8000", "server:flask_app"]

  logspout:
    environment:
      ROUTE_URIS: syslog://logs4.papertrailapp.com:35625
