version: '2'

services:
  web:
    command: ["gunicorn", "--workers", "6", "--bind", ":8000", "--timeout", "60", "server:app"]
    logging:
        driver: syslog
        options:
            syslog-address: ${PAPERTRAIL_PRODUCTION_URL}
            tag: web

  celery:
    logging:
        driver: syslog
        options:
            syslog-address: ${PAPERTRAIL_PRODUCTION_URL}
            tag: celery

  realtime-updater:
    logging:
        driver: syslog
        options:
            syslog-address: ${PAPERTRAIL_PRODUCTION_URL}
            tag: realtime-updater

  nginx:
    logging:
        driver: syslog
        options:
            syslog-address: ${PAPERTRAIL_PRODUCTION_URL}
            tag: nginx
