version: '2'

volumes:
  elasticsearch:

services:
  web:
    build: web/
    links:
      - elasticsearch
      - redis
    depends_on:
      - logspout
    volumes:
      - ./web:/code:ro

  nginx:
    restart:
      always
    build:
      nginx/
    ports:
      - "80:80"
    volumes:
      - ./web/static:/www/static:ro
    depends_on:
      - web

  redis:
    image: redis:3.0

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    depends_on:
      - logspout

  kibana:
    build: elk/kibana/
    volumes:
      - ./elk/kibana/config/:/opt/kibana/config/
    depends_on:
      - elasticsearch
      - logspout

  logspout:
    build: logspout/
    environment:
      ROUTE_URIS: syslog://logs4.papertrailapp.com:35625
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
