version: '2'

services:
  web:
    build: web/
    links:
      - redis
    volumes:
      - ./web:/code:ro
    restart:
      always

  celery:
    build: web/
    links:
      - redis
    volumes:
      - ./web:/code:ro
    restart:
      always
    command:
      [celery, -A, app.tasks, -c, '1', worker]

  realtime_updater:
    build: web/realtime_updater/
    links:
      - redis
    volumes:
      - ./web:/code:ro
    restart:
      always

  nginx:
    restart:
      always
    build:
      nginx/
    ports:
      - "80:80"
    volumes:
      - ./web/static:/www/static:ro
    depends_on:
      - web

  redis:
    image: redis:3.2
    restart:
      always
