[default]
DEBUG_LOGGING=false
USE_DOGPILE_CACHE=false
AWS_REGION="us-east-1"

ES_ADDRESS="NO_DEFAULT_SET"
REDIS_ADDRESS="NO_DEFAULT_SET"
PAPERTRAIL_API_TOKEN="NO_DEFAULT_SET"
FULLSTORY_AUTH_TOKEN="NO_DEFAULT_SET"

JIRA_SERVER="NO_DEFAULT_SET"
JIRA_BASIC_AUTH_USERNAME="NO_DEFAULT_SET"
JIRA_BASIC_AUTH_PASSWORD="NO_DEFAULT_SET"
JIRA_PROJECT_KEY="NO_DEFAULT_SET"

JIRA_ASSIGNEE_ADWORDS="NO_DEFAULT_SET"
JIRA_ASSIGNEE_BING="NO_DEFAULT_SET"
JIRA_ASSIGNEE_SOCIAL="NO_DEFAULT_SET"
JIRA_ASSIGNEE_GRADER="NO_DEFAULT_SET"

S3_BUCKET="NO_DEFAULT_SET"
S3_KEY_PREFIX="NO_DEFAULT_SET"
AWS_ACCESS_KEY_ID="NO_DEFAULT_SET"
AWS_SECRET_ACCESS_KEY="NO_DEFAULT_SET"

PRODUCT_URL="NO_DEFAULT_SET"
KIBANA_REDIRECT_URL="NO_DEFAULT_SET"

SLACK_WEBHOOK_TRACEBACKS="NO_DEFAULT_SET"
SLACK_WEBHOOK_TRACEBACKS_ADWORDS="NO_DEFAULT_SET"
SLACK_WEBHOOK_TRACEBACKS_SOCIAL="NO_DEFAULT_SET"
SLACK_REAL_USER_TOKEN="NO_DEFAULT_SET"

AWS_SSL_CERT="NO_DEFAULT_SET"
AWS_EXTRA_SECURITY_GROUP="NO_DEFAULT_SET"
JAEGER_REPORTING_HOST="NO_DEFAULT_SET"

[development]

[testing]

[ci-testing]

[production]
USE_DOGPILE_CACHE=true