apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: celery
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: celery
        tier: backend
    spec:
      containers:
        - image: topher200/assertion-context:1.0.00
          name: celery
          args:
          - celery
          - -A
          - app.tasks
          - worker
          - --concurrency
          - "1"
          envFrom:
            - configMapRef:
                name: assertion-context-env-file
          resources:
            requests:
              cpu: 1000m
              memory: 300Mi
      restartPolicy: Always
status: {}
