apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
    tier: frontend
