apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
      - image: topher200/assertion-context-nginx:0.1.00
        name: nginx
        ports:
        - containerPort: 80
      restartPolicy: Always
status: {}
